# Generated by Django 6.0 on 2025-12-21 17:01

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('tenants', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Acte',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('code', models.CharField(blank=True, max_length=64)),
                ('name', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True)),
                ('amount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='BillingItem',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('description', models.TextField(blank=True)),
                ('quantity', models.IntegerField(default=1)),
                ('unit_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('discount', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('total', models.DecimalField(decimal_places=2, default=0, max_digits=12)),
            ],
        ),
        migrations.RemoveIndex(
            model_name='appointment',
            name='core_appoin_start_t_088d11_idx',
        ),
        migrations.RemoveIndex(
            model_name='billing',
            name='core_billin_status_b90af3_idx',
        ),
        migrations.RemoveIndex(
            model_name='staff',
            name='core_staff_last_na_9ea720_idx',
        ),
        migrations.AddField(
            model_name='appointment',
            name='date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='billing',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='staff',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_profile', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='appointment',
            name='status',
            field=models.CharField(choices=[('scheduled', 'Planifié'), ('checked_in', 'Enregistré'), ('completed', 'Terminé'), ('cancelled', 'Annulé')], default='scheduled', max_length=32),
        ),
        migrations.AlterField(
            model_name='billing',
            name='currency',
            field=models.CharField(choices=[('CDF', 'Franc Congolais (CDF)'), ('USD', 'Dollar US (USD)')], default='CDF', max_length=8),
        ),
        migrations.AlterField(
            model_name='staff',
            name='role',
            field=models.CharField(choices=[('doctor', 'Médecin'), ('nurse', 'Infirmier'), ('reception', 'Réceptionniste'), ('billing', 'Caissier'), ('admin', 'Administrateur')], max_length=32),
        ),
        migrations.AddIndex(
            model_name='appointment',
            index=models.Index(fields=['date'], name='core_appoin_date_a776ae_idx'),
        ),
        migrations.AddField(
            model_name='acte',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sub_actes', to='core.acte'),
        ),
        migrations.AddField(
            model_name='acte',
            name='tenant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tenants.tenant'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='acte',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.acte'),
        ),
        migrations.AddField(
            model_name='billingitem',
            name='billing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.billing'),
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='appointment',
            name='start_time',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='insurance_reference',
        ),
        migrations.RemoveField(
            model_name='billing',
            name='status',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='department',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='first_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='last_name',
        ),
        migrations.RemoveField(
            model_name='staff',
            name='license_number',
        ),
        migrations.AddIndex(
            model_name='acte',
            index=models.Index(fields=['code'], name='core_acte_code_06891c_idx'),
        ),
        migrations.AddIndex(
            model_name='acte',
            index=models.Index(fields=['name'], name='core_acte_name_84bc1f_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='acte',
            unique_together={('tenant', 'code')},
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['billing'], name='core_billin_billing_a2e2c4_idx'),
        ),
        migrations.AddIndex(
            model_name='billingitem',
            index=models.Index(fields=['acte'], name='core_billin_acte_id_362f37_idx'),
        ),
    ]
