# Generated by Django 6.0 on 2025-12-22 05:48

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_acte_billingitem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingPayment',
            fields=[
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('currency', models.CharField(default='CDF', max_length=8)),
                ('method', models.CharField(blank=True, max_length=64)),
                ('paid_at', models.DateTimeField(auto_now_add=True)),
                ('billing', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='core.billing')),
            ],
            options={
                'indexes': [models.Index(fields=['billing'], name='core_billin_billing_91cb48_idx'), models.Index(fields=['paid_at'], name='core_billin_paid_at_44f24c_idx')],
            },
        ),
    ]
